require 'erb'

task :default => :doc

def parse_csv_line(line,max_size=nil)
  row = line.split(',')
  row.each { |v| v.strip! }
  max_size = row.size if max_size.nil?
  row.slice(0,max_size)
end


task :doc do |t|
  puts "Building documentation..."

  # Read in the input file
  @data = []
  File.open('opcodes_implemented.csv') do |input|
    @titles = parse_csv_line(input.readline)
    @titles.delete_if{ |v| v.nil? or v.size<1 }
    input.each { |line| @data << parse_csv_line(line, @titles.size) }
  end
  
  # Sort by opcode
  @data.sort! {|x,y| x.first.hex <=> y.first.hex } 
  
  # Read in template, process it and store output
  template = File.read('opcodes_implemented.erb')
  File.open('opcodes_implemented.html', 'w') do |output|
    output.puts ERB.new(template).result(binding)
  end
  
  puts "Done."
end
